name: serieshub
description: Arabic-first TV series discovery and viewing app.
publish_to: "none"
version: 0.15.0+15

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.9.2
  screen_brightness: ^2.1.11
  volume_controller: ^3.4.4
  youtube_player_iframe: ^6.0.2
  shared_preferences: ^2.5.3
  http: ^1.2.2
  serieshub_providers:
    git:
      url: https://github.com/MohammedEmad333/SeriesHub-Providers.git
      ref: 237311568a638f2c313bc5b5376b914e32501607

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
